default_platform(:ios)

platform :ios do
  # ---------------------
  # Lint the podspec file
  # ---------------------
  desc "Lint the podspec" #run: bundle exec fastlane lint_podspec
  lane :lint_podspec do
    podspec = "UIComboBox.podspec"

    # CocoaPods Lint: Ensure the podspec is valid
    pod_lib_lint(
      podspec: podspec,
      allow_warnings: true, # Allow warnings if there are any, you can set this to false if you want to enforce stricter linting
      verbose: true
    )
  end

  # -------------------------
  # Build the app
  # -------------------------
  desc "Build the project"
  lane :build do
    scheme = "UIComboBoxApp" 

    # Build the example project
    gym(
      workspace: "UIComboBox.xcworkspace",  # Path to your example workspace
      scheme: scheme,
      clean: true
    )
  end

  # ------------------------------------------
  # Run tests for the pod library
  # ------------------------------------------
  desc "Run tests for the pod library"
  lane :perform_tests do
    scheme = "UIComboBoxUITests"  # Replace with the name of the library's scheme

    # Run tests using xcodebuild
    scan(
      workspace: "UIComboBox.xcworkspace", 
      scheme: scheme,
      clean: true,
      devices: ["iPhone 15"],
      skip_build: false,

      derived_data_path: "/tmp"
    )
  end

  # ----------------------
  # Run full test pipeline
  # ----------------------
  desc "Run lint, build, and tests for the pod library"
  lane :test do
    lint_podspec   # Lint the podspec
    build_example  # Build the example project
    perform_tests      # Run the tests
  end
end
