name: iOS UI Tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

    - name: Checkout repository
      uses: actions/checkout@v3

    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    - name: List Xcodes
      run: |
        echo "---------------"
        xcodebuild -version
        echo "---------------"
        xcodebuild -showsdks
        echo "---------------"
        ls -d /Applications/*.app | grep -i xcode

    - name: Install SwiftLint (Homebrew)
      run: |
        brew update
        brew install swiftlint

    - name: Run SwiftLint
      run: swiftlint

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.7
  
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
      shell: bash

    - run: echo "bundler:"
    - run: which bundler

    - name: Install Fastlane
      run: bundle install

    - name: Set up CocoaPods
      run: |
        bundle exec pod install
      shell: bash

    - name: Print selected Xcode
      run: xcode-select --print-path

    - name: List applications
      run: sudo ls -alh /Applications/

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app

    - name: Print selected Xcode 2
      run: xcode-select --print-path

    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
    
    - name: Run UI tests with Fastlane
      run: bundle exec fastlane run_ui_tests
      shell: bash

    - name: Upload .xcresult bundle
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ui-test-xcresult
        path: fastlane/test_output/*.xcresult   # Upload the .xcresult file
